### ISSUE TITLE
Log-service Autowire and bean error in service class java

### ISSUE THREAD

**Issue by msitdevops** [msitdevops/spring-microservice#3]
log_service | 2019-05-31 08:40:20.904 ERROR 1 --- [ main] o.s.b.d.LoggingFailureAnalysisReporter :
log_service |
log_service | ***************************
log_service | APPLICATION FAILED TO START
log_service | ***************************
log_service |
log_service | Description:
log_service |
log_service | Field logRepository in com.epharma.logservice.service.LogServiceImpl required a bean of type 'com.epharma.logservice.repository.LogRepository' that could not be found.
log_service |
log_service | The injection point has the following annotations:
log_service | - @org.springframework.beans.factory.annotation.Autowired(required=true)
log_service |
log_service |
log_service | Action:
log_service |
log_service | Consider defining a bean of type 'com.epharma.logservice.repository.LogRepository' in your configuration.
log_service |

I have tried giving Repository annotation to log repository interface but still facing the same error

**Comment by sgowtham36** [comment]
In log table, you can't use <import javax.persistence.Table;>;
you should use: <import org.springframework.data.cassandra.core.mapping.Table;>

Other thing:

In summaryRepository:
Query should be cassandra type, not jpa type:
import org.springframework.data.cassandra.repository.Query;
