### ISSUE TITLE
eureka client service is not able to sent heart beat

### ISSUE THREAD

**Issue by msitdevops** [msitdevops/spring-microservice#5]
I am getting this error
happening for all the services
gateway-service_1_d76dd3b83c97 | 2019-05-29 10:45:19.810 WARN 1 --- [tbeatExecutor-0] c.n.d.s.t.d.RetryableEurekaHttpClient : Request execution failed with message: java.net.ConnectException: Connection refused (Connection refused) gateway-service_1_d76dd3b83c97 | 2019-05-29 10:45:19.810 ERROR 1 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient : DiscoveryClient_GATEWAY-SERVER/d15c48a169e5:gateway-server:8765 - was unable to send heartbeat! gateway-service_1_d76dd3b83c97 | gateway-service_1_d76dd3b83c97 | com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1405) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | gateway-service_1_d76dd3b83c97 | 2019-05-29 10:45:20.813 ERROR 1 --- [tbeatExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://discovery-service:8761/eureka/} gateway-service_1_d76dd3b83c97 | gateway-service_1_d76dd3b83c97 | com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused) gateway-service_1_d76dd3b83c97 | at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1] gateway-service_1_d76dd3b83c97 | at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar!/:1.19.1] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar!/:1.19.1] gateway-service_1_d76dd3b83c97 | at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar!/:1.19.1] gateway-service_1_d76dd3b83c97 | at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1] gateway-service_1_d76dd3b83c97 | at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:529) ~[jersey-client-1.19.1.jar!/:1.19.1] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:102) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79) ~[eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1405) [eureka-client-1.9.8.jar!/:1.9.8] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171] gateway-service_1_d76dd3b83c97 | Caused by: java.net.ConnectException: Connection refused (Connection refused) gateway-service_1_d76dd3b83c97 | at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_171] gateway-service_1_d76dd3b83c97 | at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b83c97 | at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.8.jar!/:4.5.8] gateway-service_1_d76dd3b

**Comment by msitdevops** [comment]
i have run Eureka Discovery Server first by making necessary changes to docker-compose and Dockerfile's. still i am facing the same problem. I have pushed the changes to the git for reference.

image

**Comment by sgowtham36** [comment]
First of all, you should run Eureka Discovery Server. Because other microservices depend on Eureka Server.
It is pointing to localhost and Eureka is no longer running on localhost, localhost in this case is the individual containers.

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/ should be like:

eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/

You should update all microservices:
eureka:
client:
serviceUrl:
defaultZone: http://localhost:8761/eureka/ -> http://discovery-service:8761/eureka/
